### ISSUE TITLE
Tests are slow to run

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/pycyphal#292]
Consider parallelizing
https://pytest-xdist.readthedocs.io/en/latest/distribution.html
It's best to improve software because better server hardware cannot fix all the problems that good design can.

**Comment by pavel-kirienko** [comment]
Our tests are fragile enough and many of them have shared dependencies like compiled DSDL types or network interfaces. Some of them can be run in parallel, but these are fast to run already so while they are easy to parallel the benefit will be negligible. I would therefore not invest any time into this.

The CI is expected to be sped up after migration to GitHub Actions because GHA allows running much more jobs in parallel. See https://github.com/OpenCyphal/pycyphal/issues/259

Your main problem is that you are trying to use Windows for developing PyCyphal. Things normally are much more predictable on GNU/Linux.
